language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
install: "pip install -r requirements.txt"
script:
  - pylint ./RasPy
  - python -m compileall -f ./RasPy
  - nose2 -v
