language: python

python:
    - "2.7"

sudo: false

cache:
    directories:
        - $HOME/.cache/pip

install: "pip install --ignore-installed -r requirements.txt"

script:
  - pylint --rcfile pylintrc ./raspy/*.py
  - flake8 ./raspy
  - python -m compileall -f ./raspy
  - nose2 -v

notifications:
  email:
    - cyrusbuilt@gmail.com
  on_failure: change
  on_success: never